INSERT INTO guests(`created`, `name`, `surname`, `undertwelve`, `vegan_menu`) VALUES 
(now(), 'Thiago', 'da Silveira',0,0),
(now(), 'Mariana', 'Gerali',0,0),
(now(), 'Izabel', 'Vargas',0,0),
(now(), 'João', 'da Silveira',0,0),
(now(), 'Aline', 'Machado',0,0),
(now(), 'Mathaeus', 'da Silveira',0,0),
(now(), 'Bruna', 'Gauterio',0,0),
(now(), 'Ezequiel', 'da Silveira',0,0),
(now(), 'Clara', 'da Silveira',0,0),
(now(), 'Patricia', 'da Silveira',0,0),
(now(), 'João Paulo', 'da Silveira',0,0),
(now(), 'Rejane', 'da Silveira',0,0),
(now(), 'Nadia', 'Vargas',0,0),
(now(), 'Vera', 'Pacheco',0,0),
(now(), 'María Rosa', 'Rodríguez',0,0),
(now(), 'Florencia', 'Gerali',0,0),
(now(), 'Carlos', 'Rodríguez',0,0),
(now(), 'Carmen', 'Cammarano',0,0),
(now(), 'Alejandra','Rodríguez',0,0),
(now(), 'José', 'Bossano',0,0),
(now(), 'Agustín', 'Bossano',1,0),
(now(), 'Gustavo', 'Gerali',0,0),
(now(), 'Wanda', 'Baldassari',0,0),
(now(), 'Rodrigo', 'Romero',0,0),
(now(), 'Flavia', 'Cigarán',0,0),
(now(), 'Teresita', 'Olivieri',0,0),
(now(), 'José Pedro', 'Varela',0,0),
(now(), 'Gabriel', 'Durante',0,0),
(now(), 'Carol', 'Sarmento',0,0),
(now(), 'Leandro', 'Ramos',0,0),
(now(), 'Luiz', 'Ribeiro',0,0),
(now(), 'Douglas', 'Gubert',0,0),
(now(), 'Camila', 'Veiga',0,0),
(now(), 'Alan', 'Gubert',1,0),
(now(), 'Victor', 'Fleitas',0,0),
(now(), 'Ivana', 'Baldassari',0,0),
(now(), 'Germán', 'Fleitas',0,0),
(now(), 'Francina', 'Fleitas',0,0),
(now(), 'Lorena', 'Baldassari',0,0),
(now(), 'Jorge', 'Díaz',0,0),
(now(), 'Adriana', 'Díaz',0,0),
(now(), 'Enrique', 'da Silveira',0,0),
(now(), 'Federico', 'Díaz',1,0),
(now(), 'Cony', 'Díaz',1,0),
(now(), 'Sheila', 'Lima',0,0),
(now(), 'Rafael', 'Szarblewski',0,0),
(now(), 'Estela', 'Morelle',0,0),
(now(), 'Bianca', 'Darski',0,0),
(now(), 'Marden', 'Müller',0,0),
(now(), 'Roberta', 'Grudzinski',0,0),
(now(), 'Claudio', 'Coutto',0,0),
(now(), 'Jennifer', 'Salaberry',0,0),
(now(), 'Raúl', 'Díaz',0,0),
(now(), 'Ingrid', 'Machado',0,0),
(now(), 'Hernán', 'García',0,0),
(now(), 'Nicolás', 'Licandro',0,0),
(now(), 'Sofía', 'Pinto',0,0),
(now(), 'Matías', 'Vain',0,0),
(now(), 'Néstor', 'Ferreira',0,0),
(now(), 'Rodolfo', 'Pereira',0,0),
(now(), 'Valentina', 'Blanco',0,0),
(now(), 'Nicolás', 'Zuccotti',0,0),
(now(), 'Rodrigo', 'Tranquilo',0,0),
(now(), 'Tatiana', 'Díaz',0,0),
(now(), 'Brian', 'Flores',0,0);